### PR TITLE
Windows Support

### PR DESCRIPTION
**Pull request by Sean-Der**
This is broken, but WIP

### CODE REVIEW

**Comment by disa6302** [comment]
The bat script in windows would be used by customers as well, right? 

If that is the case, should we move the file outside .github and add instructions in the README.md?

**Comment by Sean-Der** [comment]
I wasn't planning for customers to use @disa6302. Personally I would rather users invoke the commands themselves!

I want to have this all inline in the `.travis.yml` but I couldn't get bash on Windows to execute :/

**Comment by disa6302** [comment]
@Sean-Der,  I am good with that! As long as we list out the dependencies with the version information we tested with (maybe) for running our SDKs on Windows in the cpp SDK, it should be good.

**Comment by Sean-Der** [comment]
@disa6302 agree, after this I want to go back and every README will have a `building on Windows` note.

My end goal is that everything should have the same exact flow, but then we have little notes (If you are building on Windows/Mac/Linux do this!) 

I think we will see more stability/less config drift that way! Maybe I am wrong, but that is my hope at least :)

**Pull request merged**
