### PR TITLE
Only needed by windows.

### PR DESCRIPTION
**Pull request by awsa2ron**
CURL_STATIC_CRT "Set to ON to build libcurl with static CRT on Windows (/MT)."
https://github.com/winlibs/cURL/blob/master/CMakeLists.txt#L78

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by MushMal** [comment]
@lherman-cs Could you please take a look at this?

**Review by lherman-cs — APPROVED** [review]
LGTM

**Comment by lherman-cs** [comment]
@awsa2ron since this is a build system change, we need to recreate this PR using our accounts so that the CI can run properly and make sure that it doesn't break any of platforms in the CI.

**Comment by lherman-cs** [comment]
@awsa2ron recreated the PR https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/pull/135. Therefore, I'm closing this.

**Pull request closed without merging**
