### PR TITLE
Added 'Use Local OpenSSL Build' Flag and Functionality to CMake

### PR DESCRIPTION
**Pull request by stefankiesz**
Added local OpenSSL build CMake flag and functionality. LOCAL_OPENSSL_BUILD defaults to OFF. When it is specified to be ON, the local OpenSSL build will be used when CMake is called.

For pkg-config to find openssl@1.1 you MUST set:
`export PKG_CONFIG_PATH="<your_path>/openssl@1.1/lib/pkgconfig"
`
If you need to have openssl@1.1 first in your PATH, run:
`echo 'export PATH="/opt/homebrew/opt/openssl@1.1/bin:$PATH"' >> ~/.zshrc
`
For compilers to find openssl@1.1 you may need to set:
```
export LDFLAGS="-L/opt/homebrew/opt/openssl@1.1/lib"
export CPPFLAGS="-I/opt/homebrew/opt/openssl@1.1/include"
```

May have to specify path to OpenSSL root directory when calling Cmake:
`-DOPENSSL_ROOT_DIR=<your_path>
`

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by disa6302 — COMMENTED** [review]
Can we add a CI job on MacOS to test this flag out?
https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/develop/.github/workflows/ci.yml

**Comment by stefankiesz** [comment]
OK CI job with flag has been added. I also had to specify the PKG_CONFIG_PATH env variable for the local OpenSSL build to work.

**Review by disa6302 — APPROVED** [review]

**Comment by stefankiesz** [comment]
ReadMe instructions on how to use these compile time CMake flags have been added.

**Review by hassanctech — APPROVED** [review]
lgtm

**Review by jdelapla — APPROVED** [review]

**Pull request merged**
